/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MKL25Z128xxx4
package_id: MKL25Z128VLK4
mcu_data: ksdk2_0
processor_version: 7.0.1
board: FRDM-KL25Z
pin_labels:
- {pin_num: '22', pin_signal: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1, label: 'J10[11]', identifier: Saida_DAC}
- {pin_num: '30', pin_signal: TSI0_CH5/PTA4/I2C1_SDA/TPM0_CH1/NMI_b, label: 'J1[10]/D4', identifier: PWM2}
- {pin_num: '31', pin_signal: PTA5/USB_CLKIN/TPM0_CH2, label: 'J1[12]/D5', identifier: PWM3}
- {pin_num: '32', pin_signal: PTA12/TPM1_CH0, label: 'J1[8]/D3', identifier: On_off_sensores}
- {pin_num: '33', pin_signal: PTA13/TPM1_CH1, label: 'J2[2]/D8', identifier: add_sensor2}
- {pin_num: '43', pin_signal: ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0, label: 'J10[2]/A0', identifier: Sensor_1_e_2;Sensor_1_e_2_SCL}
- {pin_num: '44', pin_signal: ADC0_SE9/TSI0_CH6/PTB1/I2C0_SDA/TPM1_CH1, label: 'J10[4]/A1', identifier: Sensor_1_e_2;Sensor_1_e2;Sensor_1_e_2_SDA}
- {pin_num: '56', pin_signal: ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0, label: 'J10[12]/U6[31]/A5', identifier: Sensor_3_e_4;Sensor_3_e_4_SCL}
- {pin_num: '57', pin_signal: ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1, label: 'J10[10]/A4', identifier: Sensor_3e4;Sensor_3e_4_SDA;Sensor_3_e_4_SDA}
- {pin_num: '62', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT, label: 'J1[9]', identifier: Sensor_4}
- {pin_num: '63', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/SPI0_MISO, label: 'J1[11]', identifier: Sensor_3}
- {pin_num: '67', pin_signal: PTC10/I2C1_SCL, label: 'J1[13]', identifier: Sensor_2}
- {pin_num: '68', pin_signal: PTC11/I2C1_SDA, label: 'J1[15]', identifier: Sensor_1}
- {pin_num: '73', pin_signal: PTD0/SPI0_PCS0/TPM0_CH0, label: 'J2[6]/D10', identifier: PWM1}
- {pin_num: '76', pin_signal: PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI, label: 'J2[10]/D12', identifier: PWM4}
- {pin_num: '77', pin_signal: PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4, label: 'J1[6]/D2', identifier: PWM5}
- {pin_num: '78', pin_signal: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5, label: 'J2[4]/D9', identifier: PWM6}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '28', peripheral: UART0, signal: TX, pin_signal: TSI0_CH3/PTA2/UART0_TX/TPM2_CH1}
  - {pin_num: '27', peripheral: UART0, signal: RX, pin_signal: TSI0_CH2/PTA1/UART0_RX/TPM2_CH0}
  - {pin_num: '73', peripheral: TPM0, signal: 'CH, 0', pin_signal: PTD0/SPI0_PCS0/TPM0_CH0, direction: OUTPUT}
  - {pin_num: '43', peripheral: I2C0, signal: SCL, pin_signal: ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0, identifier: Sensor_1_e_2_SCL}
  - {pin_num: '56', peripheral: I2C1, signal: SCL, pin_signal: ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0, identifier: Sensor_3_e_4_SCL}
  - {pin_num: '57', peripheral: I2C1, signal: SDA, pin_signal: ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1, identifier: Sensor_3_e_4_SDA}
  - {pin_num: '22', peripheral: DAC0, signal: OUT, pin_signal: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1}
  - {pin_num: '44', peripheral: I2C0, signal: SDA, pin_signal: ADC0_SE9/TSI0_CH6/PTB1/I2C0_SDA/TPM1_CH1, identifier: Sensor_1_e_2_SDA}
  - {pin_num: '30', peripheral: TPM0, signal: 'CH, 1', pin_signal: TSI0_CH5/PTA4/I2C1_SDA/TPM0_CH1/NMI_b, direction: OUTPUT, pull_enable: disable}
  - {pin_num: '31', peripheral: TPM0, signal: 'CH, 2', pin_signal: PTA5/USB_CLKIN/TPM0_CH2, direction: OUTPUT}
  - {pin_num: '76', peripheral: TPM0, signal: 'CH, 3', pin_signal: PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI, direction: OUTPUT}
  - {pin_num: '77', peripheral: TPM0, signal: 'CH, 4', pin_signal: PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4, direction: OUTPUT}
  - {pin_num: '78', peripheral: TPM0, signal: 'CH, 5', pin_signal: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5, direction: OUTPUT}
  - {pin_num: '67', peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: PTC10/I2C1_SCL, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '68', peripheral: GPIOC, signal: 'GPIO, 11', pin_signal: PTC11/I2C1_SDA, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '62', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '63', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/SPI0_MISO, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t Sensor_4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC5 (pin 62)  */
    GPIO_PinInit(BOARD_INITPINS_Sensor_4_GPIO, BOARD_INITPINS_Sensor_4_PIN, &Sensor_4_config);

    gpio_pin_config_t Sensor_3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC6 (pin 63)  */
    GPIO_PinInit(BOARD_INITPINS_Sensor_3_GPIO, BOARD_INITPINS_Sensor_3_PIN, &Sensor_3_config);

    gpio_pin_config_t Sensor_2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC10 (pin 67)  */
    GPIO_PinInit(BOARD_INITPINS_Sensor_2_GPIO, BOARD_INITPINS_Sensor_2_PIN, &Sensor_2_config);

    gpio_pin_config_t Sensor_1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC11 (pin 68)  */
    GPIO_PinInit(BOARD_INITPINS_Sensor_1_GPIO, BOARD_INITPINS_Sensor_1_PIN, &Sensor_1_config);

    /* PORTA1 (pin 27) is configured as UART0_RX */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_UART_RX_PORT, BOARD_INITPINS_DEBUG_UART_RX_PIN, kPORT_MuxAlt2);

    /* PORTA2 (pin 28) is configured as UART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_UART_TX_PORT, BOARD_INITPINS_DEBUG_UART_TX_PIN, kPORT_MuxAlt2);

    /* PORTA4 (pin 30) is configured as TPM0_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_PWM2_PORT, BOARD_INITPINS_PWM2_PIN, kPORT_MuxAlt3);

    PORTA->PCR[4] = ((PORTA->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable));

    /* PORTA5 (pin 31) is configured as TPM0_CH2 */
    PORT_SetPinMux(BOARD_INITPINS_PWM3_PORT, BOARD_INITPINS_PWM3_PIN, kPORT_MuxAlt3);

    /* PORTB0 (pin 43) is configured as I2C0_SCL */
    PORT_SetPinMux(BOARD_INITPINS_Sensor_1_e_2_SCL_PORT, BOARD_INITPINS_Sensor_1_e_2_SCL_PIN, kPORT_MuxAlt2);

    /* PORTB1 (pin 44) is configured as I2C0_SDA */
    PORT_SetPinMux(BOARD_INITPINS_Sensor_1_e_2_SDA_PORT, BOARD_INITPINS_Sensor_1_e_2_SDA_PIN, kPORT_MuxAlt2);

    /* PORTC1 (pin 56) is configured as I2C1_SCL */
    PORT_SetPinMux(BOARD_INITPINS_Sensor_3_e_4_SCL_PORT, BOARD_INITPINS_Sensor_3_e_4_SCL_PIN, kPORT_MuxAlt2);

    /* PORTC10 (pin 67) is configured as PTC10 */
    PORT_SetPinMux(BOARD_INITPINS_Sensor_2_PORT, BOARD_INITPINS_Sensor_2_PIN, kPORT_MuxAsGpio);

    /* PORTC11 (pin 68) is configured as PTC11 */
    PORT_SetPinMux(BOARD_INITPINS_Sensor_1_PORT, BOARD_INITPINS_Sensor_1_PIN, kPORT_MuxAsGpio);

    /* PORTC2 (pin 57) is configured as I2C1_SDA */
    PORT_SetPinMux(BOARD_INITPINS_Sensor_3_e_4_SDA_PORT, BOARD_INITPINS_Sensor_3_e_4_SDA_PIN, kPORT_MuxAlt2);

    /* PORTC5 (pin 62) is configured as PTC5 */
    PORT_SetPinMux(BOARD_INITPINS_Sensor_4_PORT, BOARD_INITPINS_Sensor_4_PIN, kPORT_MuxAsGpio);

    /* PORTC6 (pin 63) is configured as PTC6 */
    PORT_SetPinMux(BOARD_INITPINS_Sensor_3_PORT, BOARD_INITPINS_Sensor_3_PIN, kPORT_MuxAsGpio);

    /* PORTD0 (pin 73) is configured as TPM0_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_PWM1_PORT, BOARD_INITPINS_PWM1_PIN, kPORT_MuxAlt4);

    /* PORTD3 (pin 76) is configured as TPM0_CH3 */
    PORT_SetPinMux(BOARD_INITPINS_PWM4_PORT, BOARD_INITPINS_PWM4_PIN, kPORT_MuxAlt4);

    /* PORTD4 (pin 77) is configured as TPM0_CH4 */
    PORT_SetPinMux(BOARD_INITPINS_PWM5_PORT, BOARD_INITPINS_PWM5_PIN, kPORT_MuxAlt4);

    /* PORTD5 (pin 78) is configured as TPM0_CH5 */
    PORT_SetPinMux(BOARD_INITPINS_PWM6_PORT, BOARD_INITPINS_PWM6_PIN, kPORT_MuxAlt4);

    /* PORTE30 (pin 22) is configured as DAC0_OUT */
    PORT_SetPinMux(BOARD_INITPINS_Saida_DAC_PORT, BOARD_INITPINS_Saida_DAC_PIN, kPORT_PinDisabledOrAnalog);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK | SIM_SOPT5_UART0RXSRC_MASK)))

                  /* UART0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX)

                  /* UART0 receive data source select: UART0_RX pin. */
                  | SIM_SOPT5_UART0RXSRC(SOPT5_UART0RXSRC_UART_RX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
